AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to launch an EC2 instance with Apache webserver"

Resources:
  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: "kobbylenz"
      SecurityGroups:
        - !Ref EC2InstanceSecurityGroup
      ImageId: "ami-0ea3c35c5c3284d82"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            apt update -y
            apt install apache2 git -y
            systemctl start apache2
            systemctl enable apache2
            cd /tmp
            git clone https://github.com/Kobbyone4real/aws-web-deployment.git
            mv /tmp/aws-web-deployment/index.html /var/www/html/index.html
            chown -R www-data:www-data /var/www/html
            chmod -R 755 /var/www/html

Outputs:
  InstancePublicIP:
    Description: "Public IP of the EC2 instance"
    Value: !GetAtt EC2Instance.PublicIp
